GET {{host}}
Accept: application/json

### Register

POST {{host}}/auth/register
Content-Type: application/json

{
  "client_id": "e0ca5797b2d2b0b63fe1346c5994e7af",
  "username": "test11@test.com",
  "password": "test"
}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Login

POST {{host}}/auth/token
Content-Type: application/json

{
  "client_id": "e0ca5797b2d2b0b63fe1346c5994e7af",
  "username": "test@test.com",
  "password": "test",
  "grant_type": "password"
}

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
%}

### refresh token

POST {{host}}/auth/token
Content-Type: application/json

{
  "client_id": "e0ca5797b2d2b0b63fe1346c5994e7af",
  "refresh_token": "{{refresh_token}}",
  "grant_type": "refresh_token"
}

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
%}

### logout

POST {{host}}/auth/logout
Content-Type: application/json

{
  "client_id": "e0ca5797b2d2b0b63fe1346c5994e7af",
  "refresh_token": "{{refresh_token}}",
}

###

GET {{host}}/info
Content-Type: application/json
Authorization: Bearer {{access_token}}

###

POST {{host}}/auth/reset
Content-Type: application/json

{
  "email": "tikiram@icloud.com"
}

