GET http://localhost:3000
Accept: application/json

### Register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "username": "test6@test.com",
  "password": "test"
}

### Login

POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "username": "test6@test.com",
  "password": "test",
  "grand_type": "password"
}

> {%
  client.global.set("access_token", response.body.access_token);
  client.global.set("refresh_token", response.body.refresh_token);
%}

### refresh token

POST http://localhost:3000/auth/token
Content-Type: application/json

{
  "refresh_token": "{{refresh_token}}",
  "grand_type": "refresh_token"
}

> {%
  client.global.set("access_token", response.body.access_token);
%}

###

GET http://localhost:3000/info
Content-Type: application/json
Authorization: Bearer {{access_token}}
