GET {{host}}
Accept: application/json

### Register

POST {{host}}/b/v1/auth/register
Content-Type: application/json
x-client-type: service

{
  "email": "test3@test.com",
  "password": "test"
}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}

### Sign In

POST {{host}}/b/v1/auth/login
Content-Type: application/json
x-client-type: service

{
  "email": "test3@test.com",
  "password": "test"
}

> {%
    client.global.set("access_token", response.body.access_token);
    client.global.set("refresh_token", response.body.refresh_token);
%}


### pools

GET {{host}}/b/v1/pools
Content-Type: application/json
Authorization: Bearer {{access_token}}

### pools

POST {{host}}/b/v1/pools
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "kid": "iia_dev",
  "private_key": "test",
  "public_key": "test"
}