
POST https://api.mailgun.net/v3/sandbox85f111ab54b9402baec8bbf27f45e1b3.mailgun.org/messages
Authorization: Basic api token
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="from"

Excited User <mailgun@sandbox85f111ab54b9402baec8bbf27f45e1b3.mailgun.org>
--WebAppBoundary
Content-Disposition: form-data; name="to"

YOU@sandbox85f111ab54b9402baec8bbf27f45e1b3.mailgun.org
--WebAppBoundary
Content-Disposition: form-data; name="subject"

Hello
--WebAppBoundary
Content-Disposition: form-data; name="text"

This is some text
--WebAppBoundary--
