POST https://api.sendgrid.com/v3/mail/send
Authorization: Bearer token
Content-Type: application/json

{
  "personalizations": [
    {
      "to": [
        {
          "email": "tikiram.ruiz@gmail.com"
        }
      ]
    }
  ],
  "from": {
    "email": "no-reply@equanimousoft.com"
  },
  "subject": "Sending with SendGrid is Fun 2",
  "content": [
    {
      "type": "text/plain",
      "value": "and easy to do anywhere, even with cURL 2"
    }
  ]
}
